import { MathAction } from '../types/types';

export const mathActions: MathAction[] = [
    {
        id: 'DERIVATIVE',
        labelEs: 'Derivar',
        labelEn: 'Derivative',
        latexTemplate: '\\frac{d}{dx}(□)',
        sympyTemplate: 'diff($0, x)',
        numPlaceholders: 1,
    },
    {
        id: 'INTEGRAL',
        labelEs: 'Integral',
        labelEn: 'Integral',
        latexTemplate: '∫(□)dx',
        sympyTemplate: 'integrate($0, x)',
        numPlaceholders: 1,
    },
    {
        id: 'LIMIT',
        labelEs: 'Límite',
        labelEn: 'Limit',
        latexTemplate: 'lim(□)',
        sympyTemplate: 'limit($0, x, 0)',
        numPlaceholders: 1,
    },
    {
        id: 'SOLVE',
        labelEs: 'Resolver',
        labelEn: 'Solve',
        latexTemplate: 'solve(□)',
        sympyTemplate: 'solve($0, x)',
        numPlaceholders: 1,
    },
    {
        id: 'SIMPLIFY',
        labelEs: 'Simplificar',
        labelEn: 'Simplify',
        latexTemplate: 'simplify(□)',
        sympyTemplate: 'simplify($0)',
        numPlaceholders: 1,
    },
    {
        id: 'FACTOR',
        labelEs: 'Factorizar',
        labelEn: 'Factor',
        latexTemplate: 'factor(□)',
        sympyTemplate: 'factor($0)',
        numPlaceholders: 1,
    },
    {
        id: 'SIN',
        labelEs: 'Seno',
        labelEn: 'Sine',
        latexTemplate: 'sin(□)',
        sympyTemplate: 'sin($0)',
        numPlaceholders: 1,
    },
    {
        id: 'COS',
        labelEs: 'Coseno',
        labelEn: 'Cosine',
        latexTemplate: 'cos(□)',
        sympyTemplate: 'cos($0)',
        numPlaceholders: 1,
    },
    {
        id: 'TAN',
        labelEs: 'Tangente',
        labelEn: 'Tangent',
        latexTemplate: 'tan(□)',
        sympyTemplate: 'tan($0)',
        numPlaceholders: 1,
    },
];

export const operatorActions: MathAction[] = [
    {
        id: 'SQRT',
        labelEs: '√',
        labelEn: '√',
        latexTemplate: '√(□)',
        sympyTemplate: 'sqrt($0)',
        numPlaceholders: 1,
    },
    {
        id: 'POWER',
        labelEs: 'x^n',
        labelEn: 'x^n',
        latexTemplate: '(□)^(□)',
        sympyTemplate: '($0)**($1)',
        numPlaceholders: 2,
    },
    {
        id: 'FRACTION',
        labelEs: 'a/b',
        labelEn: 'a/b',
        latexTemplate: '(□)/(□)',
        sympyTemplate: '($0)/($1)',
        numPlaceholders: 2,
    },
    {
        id: 'PI',
        labelEs: 'π',
        labelEn: 'π',
        latexTemplate: 'π',
        sympyTemplate: 'pi',
        numPlaceholders: 0,
    },
];
